version: '3'
services:
     # Frontend React
#  frontend:
#    build:
#     context: ./front
#     dockerfile: Dockerfile.react
#    ports:
#     - "3000:3000"

  backend:
    image: daimainardi/nutrifit-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/nutrifit_api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3003
    restart: on-failure

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3003
      MYSQL_DATABASE: nutrifit_api
    restart: on-failure